---
- name: Variables Demo
  hosts: servers
  become: yes
  vars:
    myusername: Debilicious

  tasks:
    - name: Update static page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynam.html
